name: test automation pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

      action:
        description: 'Select action to perform'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - test
          - rollback
