name: test automation pipeline

on:
  workflow_dispatch:
    inputs:
      automation_type:
        description: 'Select automation type'
        required: true
        default: 'App logic'
        type: choice
        options:
          - App logic
          - Integration

      browsers:
        description: 'Select automation type'
        required: true
        default: 'App logic'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - UAT
          - PROD

      scope:
        description: 'Select scope of test for App logic tests'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - regression
          - pull request

jobs:
  test_automation:
    runs-on: ubuntu-latest
    name: Run Playwright tests in subfolder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install
        working-directory: ./Playwright

      - name: Set up Playwright
        run: yarn playwright install 
        working-directory: ./Playwright

      - name: Install Playwright Browsers
        run: |
          case "${{ github.event.inputs.browsers }}" in
            chromium)
              yarn playwright install --with-deps chromium
              ;;
            firefox)
              yarn playwright install --with-deps firefox
              ;;
            webkit)
              yarn playwright install --with-deps webkit
              ;;
            *)
              echo "Invalid browser selection: ${{ github.event.inputs.browsers }}"
              exit 1
              ;;
          esac
        working-directory: ./Playwright

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.inputs.environment}}
          projects: ${{ github.event.inputs.browsers }}
        run: yarn playwright test
        working-directory: ./Playwright