name: test automation pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - qa
          - test
          - uat
          - prod
      action:
        description: 'Select action to perform'
        required: true
        default: 'scope'
        type: choice
        options:
          - full
          - regression
          - pullrequest
