name: test automation pipeline

on:
  workflow_dispatch:
    inputs:
      automation_type:
        description: 'Select automation type'
        required: true
        default: 'App logic'
        type: choice
        options:
          - App logic
          - Integration

      browsers:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - UAT
          - PROD

      scope:
        description: 'Select scope of test for App logic tests'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - regression
          - pull request

jobs:
  test_automation:
    runs-on: ubuntu-latest
    name: Run Playwright tests
    container:
      image: mcr.microsoft.com/playwright:v1.53.2,
      env:
        PLAYWRIGHT_BROWSERS_PATH: '0'  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Install Playwright Browsers
      #   run: |
      #     case "${{ github.event.inputs.browsers }}" in
      #       chromium)
      #         yarn playwright install --with-deps chromium
      #         ;;
      #       firefox)
      #         yarn playwright install --with-deps firefox
      #         ;;
      #       webkit)
      #         yarn playwright install --with-deps webkit
      #         ;;
      #       *)
      #         echo "Invalid browser selection: ${{ github.event.inputs.browsers }}"
      #         exit 1
      #         ;;
      #     esac
      #   working-directory: ./Playwright

      - name: Install dependencies with Yarn
        run: yarn install --ignore-scripts
        working-directory: ./Playwright
      
      - name: environment info
        run:
          echo "Checking Playwright info..."
          yarn playwright --version
          echo "PLAYWRIGHT_BROWSERS_PATH=$PLAYWRIGHT_BROWSERS_PATH"
          ls -la node_modules/playwright-core/.local-browsers || true
        working-directory: ./Playwright

      - name: Run Playwright tests
        env:
          CI: true
          BASE_URL: ${{ github.event.inputs.environment }}
        run: yarn playwright test --project=${{ github.event.inputs.browsers }}
        working-directory: ./Playwright