name: test automation pipeline

on:
  workflow_dispatch:
    inputs:
      automation_type:
        description: 'Select automation type'
        required: true
        default: 'App logic'
        type: choice
        options:
          - App logic
          - Integration
          - Accessibility

      browsers:
        description: 'Select browser'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

      environment:
        description: 'Select environment'
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - UAT
          - PROD

      scope:
        description: 'Select scope of test for App logic tests'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - full
          - regression
          - pullrequest

jobs:
  App_logic_tests:
    if: (github.event.inputs.automation_type == 'App logic')
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.1
      env:
        PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies with Yarn
        run: yarn install --ignore-scripts
        working-directory: ./Playwright

      - name: Run Playwright tests
        env:
          CI: true
          BASE_URL: ${{ github.event.inputs.environment }}
        run: |
          if [[ "${{ github.event.inputs.scope }}" == "all" ]]; then
            yarn playwright test tests/e2e --project=${{ github.event.inputs.browsers }}
          else
            yarn playwright test tests/e2e --project=${{ github.event.inputs.browsers }} --grep=@${{ github.event.inputs.scope }}
          fi
        working-directory: ./Playwright

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: ./Playwright/playwright-report

  Integration_tests:
    if: (github.event.inputs.automation_type == 'Integration')
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.2
      env:
        PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies with Yarn
        run: yarn install --ignore-scripts
        working-directory: ./Integration
      
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: ./Integration
  
  Accessibility_tests:
    if: (github.event.inputs.automation_type == 'Accessibility')
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.2
      env:
        PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies with Yarn
        run: yarn install --ignore-scripts
        working-directory: ./Playwright
      
      - name: Run Playwright tests
        run: yarn playwright test tests/accessibility --project=${{ github.event.inputs.browsers }}
        working-directory: ./Playwright
      
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-accessibility-report
          path: ./Playwright/playwright-report
