name: test automation pipeline

on:
  workflow_dispatch:
    inputs:
      automation_type:
        description: 'Select automation type'
        required: true
        default: 'App logic'
        type: choice
        options:
          - App logic
          - Integration

      environment:
        description: 'Select environment'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - test
          - uat
          - prod

      scope:
        description: 'Select scope of test for App logic tests'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - regression
          - pull request

jobs:
  test_automation:
    runs-on: ubuntu-latest
    name: Run Playwright tests in subfolder
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install
        working-directory: ./Playwright

      - name: Install Playwright Browsers
        run: yarn create playwright
        working-directory: ./Playwright

      - name: Run Playwright tests
        run: npx playwright test --baseURL='QA'
        working-directory: ./Playwright